pipeline {
    agent any

    environment {
        VENV = "venv"
        REPO_URL = "https://github.com/yourusername/alx-backend-python.git"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git credentialsId: 'github-credentials', 
                    url: '${REPO_URL}', 
                    branch: 'main'
                sh 'git branch'
            }
        }

        stage('Setup Python Environment') {
            steps {
                sh '''
                python3 -m venv $VENV
                . $VENV/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . $VENV/bin/activate
                pip3 install pytest pytest-cov
                pytest messaging_app --junitxml=test-results.xml --cov=messaging_app --cov-report=html --cov-report=xml
                '''
            }
        }
    }

    post {
        always {
            junit 'test-results.xml'
            publishHTML([
                reportDir: 'htmlcov',
                reportFiles: 'index.html',
                reportName: 'Coverage Report'
            ])
        }
        
        success {
            echo 'Pipeline succeeded!'
        }
        
        failure {
            echo 'Pipeline failed!'
        }
    }
}
