pipeline{
    agent any

    environment{
        VENV="venv"
    }

    stages{

        stage('checkout code'){
            steps{
                git credentialsId:'github-creds',
                url:'https://github.com/kennydasilva/alx-backend-python.git'
            }
        }


        stage('Setup Python Environment'){
            steps{
                sh '''
                python3 -m venv $VENV
                . $VENV/bin/activate
                pip install --upgrade pip
                pip install -r messaging_app/requirements.txt
                 '''
            }
        }

        stage('Run Tests'){
            steps{
                sh '''
                . $VENV/bin/activate
                pytest messaging_app --junitxml=test-results.xml'''
            }
        }
    }

    post{
        always{
            junit 'test-results.xml'
        }
    }
}