pipeline {
    agent any

    environment {
        VENV = "venv"
    }

    stages {

        stage('Setup Python Environment') {
                steps {
                    sh '''
                    python3 -m venv venv
                    venv/bin/python -m ensurepip --upgrade
                    venv/bin/python -m pip install "pip<24.1"
                    venv/bin/pip install -r messaging_app/requirements.txt
                    '''
                }
        }


        stage('Run Tests') {
            steps {
                sh '''
                $VENV/bin/python -m pytest messaging_app --junitxml=test-results.xml
                '''
            }
        }
    }

    post {
        always {
            junit 'test-results.xml'
        }
    }
}